spring:
  datasource:
    url: jdbc:h2:mem:menu
    driver-class-name: org.h2.Driver
    username: menu
    password: menu
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
